using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using HyperRTS.Simulation.Common;
using NUnit.Framework;
using UnityEditor.PackageManager;

namespace HyperRTS.Editor.Tests
{
    /// <summary>Source layout rules: namespaces follow folders and Simulation modules stay layered.</summary>
    public class ModuleLayoutTests
    {
        // Feature pairs that legitimately read each other's components. Shrink this list; never grow it casually:
        // a new pair usually means a shared type belongs in Common or a lower module.
        private static readonly string[] AllowedTwoWayPairs =
        {
            "AI <-> Match",
            "Buildings <-> Production",
            "Buildings <-> Selection",
            "Combat <-> Orders",
            "Combat <-> Transport",
            "Match <-> Production",
            "Orders <-> Transport",
            "Production <-> Upgrades",
            "Selection <-> Transport",
        };

        private static readonly Regex Namespace = new(@"^namespace ([\w.]+)", RegexOptions.Multiline);
        private static readonly Regex SimulationUsing = new(@"^using HyperRTS\.Simulation\.(\w+)", RegexOptions.Multiline);

        private static string PackageRoot =>
            PackageInfo.FindForAssembly(typeof(AuthoringBehaviour).Assembly).resolvedPath;

        [Test]
        public void NamespacesFollowFolders()
        {
            var wrong = new List<string>();
            foreach (var path in Directory.EnumerateFiles(PackageRoot, "*.cs", SearchOption.AllDirectories))
            {
                var text = File.ReadAllText(path);
                if (text.Contains("<auto-generated>"))
                {
                    continue;
                }

                var folder = RelativeTo(PackageRoot, Path.GetDirectoryName(path));
                var expected = "HyperRTS." + folder.Replace(Path.DirectorySeparatorChar, '.');
                var actual = Namespace.Match(text).Groups[1].Value;
                if (actual != expected)
                {
                    wrong.Add($"{folder}/{Path.GetFileName(path)}: {actual}");
                }
            }

            Assert.IsEmpty(wrong, "Namespace must be HyperRTS.<folder path>:\n" + string.Join("\n", wrong));
        }

        [Test]
        public void CommonDependsOnNoOtherModule()
        {
            var dependencies = SimulationDependencies();
            var common = dependencies.TryGetValue("Common", out var found) ? found : new HashSet<string>();

            Assert.IsEmpty(common, "Common is the base module: " + string.Join(", ", common));
        }

        [Test]
        public void NoNewTwoWayModuleDependencies()
        {
            var dependencies = SimulationDependencies();
            var pairs = new List<string>();
            foreach (var pair in dependencies)
            {
                var module = pair.Key;
                var uses = pair.Value;
                // Ordinal order visits each pair once.
                foreach (var other in uses.Where(other => string.CompareOrdinal(module, other) < 0))
                {
                    if (dependencies.TryGetValue(other, out var back) && back.Contains(module))
                    {
                        pairs.Add($"{module} <-> {other}");
                    }
                }
            }

            var added = pairs.Except(AllowedTwoWayPairs).ToList();
            var resolved = AllowedTwoWayPairs.Except(pairs).ToList();
            Assert.IsEmpty(added, "New two-way module dependencies:\n" + string.Join("\n", added));
            Assert.IsEmpty(resolved, "No longer two-way, remove from the allowlist:\n" + string.Join("\n", resolved));
        }

        /// <summary>
        /// Simulation module (top folder) to the other Simulation modules its runtime code imports. Authoring files are
        /// left out: they assemble prefabs from every module's components.
        /// </summary>
        private static Dictionary<string, HashSet<string>> SimulationDependencies()
        {
            var root = Path.Combine(PackageRoot, "Simulation");
            var result = new Dictionary<string, HashSet<string>>();
            foreach (var path in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories))
            {
                var module = RelativeTo(root, path).Split(Path.DirectorySeparatorChar)[0];
                if (module == "Tests" || module.EndsWith(".cs") || path.EndsWith("Authoring.cs"))
                {
                    continue;
                }

                if (!result.TryGetValue(module, out var uses))
                {
                    result[module] = uses = new HashSet<string>();
                }

                foreach (Match match in SimulationUsing.Matches(File.ReadAllText(path)))
                {
                    if (match.Groups[1].Value != module)
                    {
                        uses.Add(match.Groups[1].Value);
                    }
                }
            }

            return result;
        }

        // Path.GetRelativePath is missing from the .NET Framework profile editor code may compile against.
        private static string RelativeTo(string root, string path) =>
            Path.GetFullPath(path).Substring(Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar).Length + 1);
    }
}
