using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using HyperRTS.Simulation.Common;
using NUnit.Framework;
using UnityEditor.PackageManager;

namespace HyperRTS.Editor.Tests
{
    /// <summary>Source layout rules: namespaces follow folders, modules stay layered, authoring files hold authoring.</summary>
    public class ModuleLayoutTests
    {
        // Simulation modules, lowest first: each one may use only the modules before it.
        private static readonly string[] Layers =
        {
            "Common", "Navigation", "Stats", "Power", "Vision", "Spatial", "Selection", "Orders", "Audio", "Combat",
            "Transport", "Air", "Units", "Resources", "Match", "Production", "Upgrades", "Buildings", "Abilities",
            "Fields", "Veterancy", "Capture", "AI", "GameEntities", "Commands", "Interaction", "Replays",
        };

        // Uses of a higher layer that are part of the design. Shrink this list; never grow it casually: a new entry
        // usually means a shared type belongs in Common or a lower module.
        private static readonly string[] AllowedBackEdges =
        {
            // Production finishes research into the player's upgrades, and upgrades are produced like units.
            "Production -> Upgrades",
        };

        private static readonly Regex Namespace = new(@"^namespace ([\w.]+)", RegexOptions.Multiline);
        private static readonly Regex SimulationUsing = new(@"^using HyperRTS\.Simulation\.(\w+)", RegexOptions.Multiline);

        // Namespace-level declarations sit at a 4-space indent; nested ones (Baker, entry classes) at 8.
        private static readonly Regex RuntimeType = new(
            @"^ {4}(?:\w+ )*(?:struct (\w+)[^{\n]*\b(?:IComponentData|IBufferElementData|ISystem|IEnableableComponent)\b|enum (\w+))",
            RegexOptions.Multiline);

        private static string PackageRoot =>
            PackageInfo.FindForAssembly(typeof(AuthoringBehaviour).Assembly).resolvedPath;

        [Test]
        public void NamespacesFollowFolders()
        {
            var wrong = new List<string>();
            foreach (var path in Directory.EnumerateFiles(PackageRoot, "*.cs", SearchOption.AllDirectories))
            {
                var text = File.ReadAllText(path);
                if (text.Contains("<auto-generated>"))
                {
                    continue;
                }

                var folder = RelativeTo(PackageRoot, Path.GetDirectoryName(path));
                var expected = "HyperRTS." + folder.Replace(Path.DirectorySeparatorChar, '.');
                var actual = Namespace.Match(text).Groups[1].Value;
                if (actual != expected)
                {
                    wrong.Add($"{folder}/{Path.GetFileName(path)}: {actual}");
                }
            }

            Assert.IsEmpty(wrong, "Namespace must be HyperRTS.<folder path>:\n" + string.Join("\n", wrong));
        }

        [Test]
        public void EveryModuleIsLayered()
        {
            var root = Path.Combine(PackageRoot, "Simulation");
            var modules = Directory.EnumerateDirectories(root).Select(Path.GetFileName).Where(name => name != "Tests")
                .ToList();

            var unlayered = modules.Except(Layers).ToList();
            var unknown = Layers.Except(modules).ToList();
            Assert.IsEmpty(unlayered, "Add these modules to Layers:\n" + string.Join("\n", unlayered));
            Assert.IsEmpty(unknown, "No such module, remove from Layers:\n" + string.Join("\n", unknown));
        }

        [Test]
        public void ModulesOnlyUseLowerLayers()
        {
            var dependencies = SimulationDependencies();
            var upward = new List<string>();
            foreach (var dependency in dependencies)
            {
                var edge = dependency.Key;
                if (!IsUpward(edge) || AllowedBackEdges.Contains(edge))
                {
                    continue;
                }

                upward.Add($"{edge} ({string.Join(", ", dependency.Value)})");
            }

            var resolved = AllowedBackEdges.Where(edge => !dependencies.ContainsKey(edge) || !IsUpward(edge)).ToList();
            Assert.IsEmpty(upward, "Uses of a higher layer (move the shared type lower):\n" + string.Join("\n", upward));
            Assert.IsEmpty(resolved, "No longer a back-edge, remove it from the allowlist:\n" +
                                     string.Join("\n", resolved));
        }

        [Test]
        public void AuthoringFilesHoldOnlyAuthoring()
        {
            var misplaced = new List<string>();
            foreach (var path in Directory.EnumerateFiles(PackageRoot, "*Authoring.cs", SearchOption.AllDirectories))
            {
                foreach (Match match in RuntimeType.Matches(File.ReadAllText(path)))
                {
                    var type = match.Groups[1].Success ? match.Groups[1].Value : match.Groups[2].Value;
                    misplaced.Add($"{RelativeTo(PackageRoot, path)}: {type}");
                }
            }

            Assert.IsEmpty(misplaced, "Runtime types belong in their own files:\n" + string.Join("\n", misplaced));
        }

        /// <summary>
        /// Each "Module -> Used" edge between Simulation modules (top folders) to the runtime files that create it.
        /// Authoring files are left out: they assemble prefabs from every module's components.
        /// </summary>
        private static Dictionary<string, List<string>> SimulationDependencies()
        {
            var root = Path.Combine(PackageRoot, "Simulation");
            var result = new Dictionary<string, List<string>>();
            foreach (var path in Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories))
            {
                var module = RelativeTo(root, path).Split(Path.DirectorySeparatorChar)[0];
                if (module == "Tests" || module.EndsWith(".cs") || path.EndsWith("Authoring.cs"))
                {
                    continue;
                }

                foreach (Match match in SimulationUsing.Matches(File.ReadAllText(path)))
                {
                    var used = match.Groups[1].Value;
                    if (used == module)
                    {
                        continue;
                    }

                    var edge = $"{module} -> {used}";
                    if (!result.TryGetValue(edge, out var files))
                    {
                        result[edge] = files = new List<string>();
                    }

                    files.Add(RelativeTo(PackageRoot, path));
                }
            }

            return result;
        }

        /// <summary>Whether a "Module -> Used" edge points at a later layer.</summary>
        private static bool IsUpward(string edge)
        {
            var modules = edge.Split(new[] { " -> " }, StringSplitOptions.None);
            return Array.IndexOf(Layers, modules[1]) > Array.IndexOf(Layers, modules[0]);
        }

        // Path.GetRelativePath is missing from the .NET Framework profile editor code may compile against.
        private static string RelativeTo(string root, string path) =>
            Path.GetFullPath(path).Substring(Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar).Length + 1);
    }
}
